# Change these first
owner: InfoBlock # Your GitHub organization or username, where this repository lives
repo: Status-Page # The name of this repository

sites:
  - name: Website (Github Domain)
    url: https://infoblock.github.io/Website/
  - name: Website (Custom Domain)
    url: https://infoblock.gq
  - name: Block A.I Website (Github Domain)
    url: https://infoblock.github.io/BlockAI/
  - name: Block A.I Website (Custom Doamin)
    url: https://blockai.infoblock.gq
  - name: Preview Website (Github Domain)
    url: https://infoblock.github.io/Preview/
  - name: Preview Website (Custom Domain)
    url: https://preview.infoblock.gq

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.infoblock.gq
  # baseUrl: /your-repo-name
  logoUrl: https://infoblock.gq/cdn/logo.png
  name: status.infoblock.gq
  introTitle: "Web & Service Stats"
  introMessage: On this Page you can see the current Status of all my Projects
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://infoblock.github.io/Website/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
