# Change these first
owner: InfoBlock # Your GitHub organization or username, where this repository lives
repo: Status-Page # The name of this repository
user-agent: InfoBlock

sites:
  - name: Website (Github Domain)
    url: https://infoblock.github.io/Website/
    icon: https://infoblock.github.io/Website/cdn/logo.png
  - name: Website (Custom Domain)
    url: https://infoblock.thedev.id
    icon: https://infoblock.github.io/Website/cdn/logo.png
  - name: Block A.I Website (Github Domain)
    url: https://block-a-i.github.io/BlockWeb/
    icon: https://block-a-i.github.io/BlockWeb/assets/BotLogo.png
  - name: Block A.I Website (Custom Domain)
    url: https://blockai.infoblock.gq
    icon: https://block-a-i.github.io/BlockWeb/assets/BotLogo.png
  - name: Preview Website (Github Domain)
    url: https://infoblock.github.io/Preview/
    icon: https://infoblock.github.io/Website/cdn/logo.png
  - name: Preview Website (Custom Domain)
    url: https://preview.infoblock.gq
    icon: https://infoblock.github.io/Website/cdn/logo.png

assignees:
  - InfoBlock

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.infoblock.gq
  # baseUrl: /your-repo-name
  logoUrl: https://infoblock.github.io/Website/cdn/logo.png
  name: status.infoblock.gq
  introTitle: "Web & Service Stats"
  introMessage: On this Page you can see the current Status of all my Projects
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://infoblock.github.io/Website/
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"

i18n:
  footer: Created by [InfoBlock](https://infoblock.github.io/Website/)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
